<?php
/**
 * AuthBase 是需要登录的时候继承就可以
 * Created by singwa
 * User: singwa
 * motto: 现在的努力是为了小时候吹过的牛逼！
 * Time: 12:27
 */
namespace app\controller;
use think\exception\HttpResponseException;
use app\BaseController;

class AuthBase extends BaseController {
    public $userId = 0;
    public $username = "";
    public $accessToken = "";
    public $isLogin = "";
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->accessToken = $this->request->header("token");

        if(!$this->accessToken || !$this->isLogin()) {
            return $this->show(config("status.not_login"), "没有登录");
        }

    }

    /**
     * 判断用户是否登录
     * @return bool
     */
    public function isLogin() {
        $userInfo = cache(config("redis.token_pre").$this->accessToken);
        if(!$userInfo) {
            return false;
        }
        if(!empty($userInfo['id']) && !empty($userInfo['username'])) {
            $this->username = $userInfo['username'];
            $this->userId = $userInfo['id'];
            return true;
        }

        return false;

    }

    public function show(...$args) {
        throw new HttpResponseException(show(...$args));
    }
}